Controllers/AjaxController.cs
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using MVC_Identity.Models;

namespace MVC_Identity.Controllers
{

    public class AjaxController : Controller
    {
        public static CreatePeopleViewModel person = new CreatePeopleViewModel();


        public IActionResult Index()
        {
            return View("Index");
        }

        [HttpGet]
        public IActionResult GetPeople() { 
            
            return PartialView("_PersonPartial", person); 
        }

        [HttpPost]
        public IActionResult GetPeople(int id)
        {
            var filteredData = person.People.Where(x => x.Id == id).ToList();


            CreatePeopleViewModel filteredModel = new CreatePeopleViewModel();


            filteredModel.People = filteredData;

            if (filteredModel.People.Count == 0)
            {
                return PartialView("_PersonPartial");
            }

            return PartialView("_PersonPartial", filteredModel);

        }

        [HttpPost]
        public IActionResult AnnihilatePerson(int id)
        {
            static string OrdinalSuffixGetter(int Id)
            {
                string number = Id.ToString();
                if (number.EndsWith("11")) return "th";
                if (number.EndsWith("12")) return "th";
                if (number.EndsWith("13")) return "th";
                if (number.EndsWith("1")) return "st";
                if (number.EndsWith("2")) return "nd";
                if (number.EndsWith("3")) return "rd";
                return "th";
            }
            if (!id.Equals(null))
            {
                try
                {
                    Person? p = person.People.FirstOrDefault(p => p.Id == id);
                    if(p!=null)
                    {
                    person.People.Remove(p);   
                    ViewBag.Statement = $" OMG! They killed {p.Name} the {p.Id}{OrdinalSuffixGetter(p.Id)}! You bastards!";
                    } else if (p!=null)
                    {
                        ViewBag.Statement = "$Stop, he's already dead!!";
                    }

                }
                catch (ArgumentOutOfRangeException aa)
                {
                    ViewBag.Statement = aa.Message;
                }
            }
            else
            {
                ViewBag.Statement = "Unable to comply!";
            }

            return PartialView("_PersonPartial", person);
        }
    }

}

Controllers/CityController.cs
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Identity.Data;
using MVC_Identity.Models;

namespace MVC_Identity.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CityController : Controller
    {
        //private static CreateCityViewModel cityViewModel = new CreateCityViewModel();
        readonly MVC_DbContext _context; // creates a readonly of DbContext

        public CityController(MVC_DbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {


            var cityList = _context.Cities.Include(c => c.Country).ToList();

            return View(cityList);
        }

        public IActionResult AddCity()
        {
            ViewBag.CountryNames = new SelectList(_context.Countries, "Id", "Name");


            return View();

        }

        [HttpPost]
        public IActionResult AddCity(CreateCityViewModel c)
        {

            if (ModelState.IsValid)
            {

                _context.Add(new City()

                {
                    Name = c.NewCity.Name,
                    CountryId = c.NewCity.CountryId,
                });


                _context.SaveChanges();

                ViewBag.Statement = $"{_context.Cities} has been added to the table!";
            }
            else
            {
                ViewBag.CountryNames = new SelectList(_context.Countries, "Id", "Name");
                ViewBag.Statement = "Please fill in the form above!";
                return View("AddCity", c);
            }
            return RedirectToAction("Index");
        }
        
        public IActionResult Delete(int id, string name)
        {
            var city = _context.Cities.FirstOrDefault(x => x.Id == id);
            if (city != null)
            {
                _context.Cities.Remove(city);
                _context.SaveChanges();

            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/DbController.cs
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Identity.Data;
using MVC_Identity.Models;

namespace MVC_Identity.Controllers
{
    
    public class DbController : Controller
    {
        private readonly MVC_DbContext _context;

        public DbController(MVC_DbContext context)
        {
            _context = context;
        }

        // GET: Db
        public async Task<IActionResult> Index()
        {
              return View(await _context.People.ToListAsync());
        }

        // GET: Db/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.People == null)
            {
                return NotFound();
            }

            var person = await _context.People
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: Db/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Db/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: Db/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.People == null)
            {
                return NotFound();
            }

            var person = await _context.People.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: Db/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Person person)
        {
            if (id != person.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PeopleExists(person.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: Db/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.People == null)
            {
                return NotFound();
            }

            var person = await _context.People
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: Db/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.People == null)
            {
                return Problem("Entity set 'MVC_DbContext.People'  is null.");
            }
            var person = await _context.People.FindAsync(id);
            if (person != null)
            {
                _context.People.Remove(person);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PeopleExists(int id)
        {
          return _context.People.Any(e => e.Id == id);
        }
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Identity.Client;
using MVC_Identity.Models;
using MVC_Identity.ViewModels;

namespace MVC_Identity.Controllers
{

    public class RoleController : Controller
    {
        readonly RoleManager<IdentityRole> _roleManager;
        readonly UserManager<ApplicationUser> _userManager;
        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View(_roleManager.Roles);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            role.NormalizedName = role.Name.ToUpper();
            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            await _roleManager.DeleteAsync(role);
            return RedirectToAction("Index");

            
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var userToDelete = await _userManager.FindByIdAsync(id);

            if (userToDelete != null)
            {
                await _userManager.DeleteAsync(userToDelete);
            }
            return RedirectToAction("ShowAllUsers");
        }

        public IActionResult AddUserToRole()
        {
            ViewBag.Users = new SelectList(_userManager.Users, "Id", "UserName");
            ViewBag.Roles = new SelectList(_roleManager.Roles, "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddUserToRole(string userId, string roleName)
        {
            var user = await _userManager.FindByIdAsync(userId);
            await _userManager.AddToRoleAsync(user, roleName);
            return RedirectToAction("Index");
        }

        public IActionResult ShowAllUsers()
        {
            return View(_userManager.Users);
        }

        public async Task<IActionResult> ShowUserRoles(string Id)
        {
            UserRoleViewModel vm = new UserRoleViewModel();
            var user = await _userManager.FindByIdAsync(Id);

            var assignedRoles = new List<string>(await _userManager.GetRolesAsync(user));
            vm.UserId = Id;
            vm.UserName = $"{user.FirstName} {user.LastName}";
            vm.Roles.AddRange(assignedRoles);
            
            return View(vm);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RemoveRoleFromUser(string rolename, string userid)
        {
            var user = await _userManager.FindByIdAsync(userid);
            await _userManager.RemoveFromRoleAsync(user, rolename);

            return RedirectToAction("ShowUserRoles", new { id = userid });
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - MVC_Identity</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/MVC_Identity.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Identity</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						@if (User.IsInRole("User") || User.IsInRole("Admin"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">People</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Ajax" asp-action="Index">Ajax</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Db" asp-action="Index">Database</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="Index">Language</a>
							</li>
						}
						@if (User.IsInRole("Admin"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">Cities</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Countries
								</a>
							</li>
						}
						@if (User.Identity.IsAuthenticated)
						{
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Identity</a>
							<ul class="dropdown-menu">
								<li class="nav-item">
									<a class="dropdown-item text-dark" asp-area="" asp-controller="Role" asp-action="ShowAllUsers">Show All Users
									</a>
								</li>
								<li class="nav-item">
									<a class="dropdown-item dropdown-item text-dark" asp-area="" asp-controller="Role" asp-action="Index">Show All Roles</a>
								</li>
							</ul>
						</li>
						}



					</ul>
					<partial name="_LoginPartial" />
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; Siavash Gosheh - MVC_Identity - @(DateTime.Now.Year) - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_PersonBodyPartial.cshtml
@model CreatePeopleViewModel
@{
	string langs = "";

}


@if (@Model != null)
{

	<div class="container">

		@foreach (var item in Model.People)

		{

			<div class="row m-1">
				<div class="col">
					<label asp-for="@item.Id" />@item.Id
				</div>
				<div class="col">
					<label asp-for="@item.Name" />@item.Name
				</div>
				<div class="col">
					<label asp-for="@item.PhoneNumber" />@item.PhoneNumber
				</div>
				<div class="col">
					<label asp-for="@item.City.Name" />@item.City.Name
				</div>
				<div class="col">
					<label asp-for="@item.City.Country.Name" />@item.City.Country.Name
				</div>

				@foreach (var lang in item.Languages) {
						langs = langs + lang.Name + " ";
					}
				<div class="col">
					<p>
					@langs
					</p>
				</div>
				@{ langs = ""; }
				<div class="col">
					<a asp-action="DeletePerson" class="btn btn-danger btn-sm"  value="Delete" asp-route-id="@item.Id" asp-route-name="@item.Name">Delete</a>
				</div>					
			</div>
		}
	</div>
}

Views/Shared/_PersonHeaderPartial.cshtml
@model CreatePeopleViewModel

@{

}

@if (@Model != null)
{
	<div class="row">
		<div class="col">
			<b>
		@(Html.DisplayNameFor(model => model.NewPerson.City.Id))
		</b>
		</div>
		<div class="col"><b>@(Html.DisplayNameFor(model => model.NewPerson.Name))</b>
		</div>
		<div class="col">
			<b>@(Html.DisplayNameFor(model => model.NewPerson.PhoneNumber))</b>
		</div>
		<div class="col">
			<b>@(Html.DisplayNameFor(model => model.NewPerson.City))</b>
		</div>
		<div class="col">
			<b>@(Html.DisplayNameFor(model => model.NewPerson.City.Country))</b>
		</div>
		<div class="col">
			<b>@(Html.DisplayNameFor(model => model.NewPerson.Languages))</b>
		</div>
		<div class="col">&nbsp;</div>
	</div>
}
else
{
	<p>No results found.</p>
}

Views/Shared/_PersonPartial.cshtml
@model CreatePeopleViewModel

<p>@ViewBag.Statement</p>
@if (@Model != null)
{
    <div class="border p-5">

    <partial name="_PersonHeaderPartial" model=@Model />
    <partial name="_PersonBodyPartial" model=@Model />
    </div>

}
else
{

    <p>No results found.</p>
}