Models/Country.cs
using System.ComponentModel.DataAnnotations;
namespace MVC_Identity.Models
{
    public class Country
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public List<City> Cities { get; set; } = new List<City>();

    }
}
 

ViewModels/CountryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_Identity.Models
{
    public class CountryViewModel
    {
        [Required]
        [Display(Name = "Country Name")]
        public string Name { get; set; }
        public List<City> Cities { get; set; } = new List<City>();
    }
}

Controllers/CountryController.cs
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using MVC_Identity.Data;
using MVC_Identity.Models;

namespace MVC_Identity.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountryController : Controller
    {
        //private static CreateCountryViewModel cityViewModel = new CreateCountryViewModel();
        readonly MVC_DbContext _context; // creates a readonly of DbContext

        public CountryController(MVC_DbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {


            var countryList = _context.Countries.ToList();

            return View(countryList);
        }
        public IActionResult AddCountry()
        {
            

            return View();

        }

        [HttpPost]
        public IActionResult AddCountry(CreateCountryViewModel C)
        {

            if (ModelState.IsValid)
            {

                _context.Add(new Country()

                {
                    Name = C.NewCountry.Name,

                });


                _context.SaveChanges();

                ViewBag.Statement = $"{C.NewCountry.Name} has been added to the table!";
            }
            else
            {
                ViewBag.Statement = "Please fill in the form above!";
                return View("AddCountry", C);
            }
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id, string name)
        {
            var country = _context.Countries.FirstOrDefault(x => x.Id == id);
            if (country != null)
            {
                _context.Countries.Remove(country);
                _context.SaveChanges();

            }
            return RedirectToAction("Index");
        }
    }
}

Views/Country/AddCountry.cshtml
@model CreateCountryViewModel

@{
	ViewData["Title"] = "Add a Country";
}


<h1>@ViewBag.Title</h1>

@{
	if (TempData.Peek("Message") != null)
	{
		<h3>@TempData.Peek("Message")</h3>
		@TempData.Remove("Message");
	}
}


<div class="row m-1">
	<label>Add a new Country</label>
	<form class="container" method="post" asp-controller="Country" asp-action="AddCountry">
		<div class="col m-1">
			<input asp-for="NewCountry.Name" placeholder="Country Name" />
			<span asp-validation-for="NewCountry.Name"></span>
		</div>
		<button class="btn btn-primary btn-sm" type="submit">Submit</button>
	</form>
</div>

<p>@ViewBag.Statement</p>

Views/Country/Index.cshtml
@model IEnumerable<Country>
@{
	ViewData["Title"] = "Countries";
}

<h1>@ViewBag.Title</h1>

@if (@Model != null)
{
	<div class="row">
		<div class="col">

			<a asp-controller="Country" asp-action="AddCountry" class="btn btn-primary btn-sm">Add</a>
		</div>
	</div>

	<div class="row">
		<div class="col">
			<b>

				@(Html.DisplayNameFor(model => model.Id))
			</b>
		</div>

		<div class="col">
			<b>

				@(Html.DisplayNameFor(model => model.Name))
			</b>
		</div>
			@if(User.IsInRole("Admin"))
			{
		<div class="col">
			&nbsp;
		</div>
			}
	</div>


	@foreach (var item in Model)

	{

		<div class="row m-1">
			<div class="col">
				<b></b>
				<label asp-for="@item.Id" />@item.Id
			</div>
			<div class="col">
				<label asp-for="@item.Name" />@item.Name
			</div>
			@if(User.IsInRole("Admin"))
			{
			<div class="col">
				<a asp-controller="Country" asp-action="Delete" class="btn btn-danger btn-sm" value="Delete" asp-route-id="@item.Id" asp-route-name="@item.Name">Delete</a>
			</div>
			}
		</div>
	}

}
else
{
	<p>No results found.</p>
}