Models/Language.cs
using System.ComponentModel.DataAnnotations;
namespace MVC_Identity.Models
{
    public class Language
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Person> People { get; set; } = new List<Person>();
    }
}

ViewModels/LanguageViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace MVC_Identity.Models
{
	public class LanguageViewModel
	{

        [Display(Name = "Langauge")]
        public string Name { get; set; }
		public List<Person> People { get; set; } = new List<Person>();
	}
}

Controllers/LanguageController.cs
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using MVC_Identity.Data;

namespace MVC_Identity.Models

{

    public class LanguageController : Controller
    {

        private static CreateLanguageViewModel languageViewModel = new CreateLanguageViewModel();
        readonly MVC_DbContext _context;
        public LanguageController(MVC_DbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            var languageList = _context.Languages.ToList();

            return View(languageList);
        }

        public IActionResult AddLanguage()
        {
           
            return View();

        }

        [HttpPost]
        public IActionResult AddLanguage(CreateLanguageViewModel l)
        {
            if (ModelState.IsValid)
            {

                _context.Add(new Language()
                {
                    Name = l.NewLanguage.Name
                });

                _context.SaveChanges();
            }
            else
            {
                ViewBag.Statement = "Please fill in the form above!";
                return View("AddLanguage", l);

            }
            return RedirectToAction("Index");

        }


        public IActionResult Delete(int id, string name)
        {
            var lang = _context.Languages.FirstOrDefault(x => x.Id == id);
            if (lang != null)
            {
                _context.Languages.Remove(lang);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Index");
        }
    }
}

Views/Language/AddLanguage.cshtml
@model CreateLanguageViewModel

@{
	ViewData["Title"] = "Add a Language";
}


<h1>@ViewBag.Title</h1>

@{
	if (TempData.Peek("Message") != null)
	{
		<h3>@TempData.Peek("Message")</h3>
		@TempData.Remove("Message")
		;
	}
}

<div class="row">
	<label>Add a new Language</label>
	<form class="container" method="post" asp-controller="Language" asp-action="AddLanguage">
		<div class="col">

			<input asp-for="NewLanguage.Name" placeholder="Language Name" />
			<span asp-validation-for="NewLanguage.Name"></span>
		</div>
		<button class="btn btn-primary btn-sm m-1" type="submit">Submit</button>
	</form>
</div>

<p>@ViewBag.Statement</p>

Views/Language/Index.cshtml
@model IEnumerable<Language>
@{
	ViewData["Title"] = "Languages";
}

<h1>@ViewBag.Title</h1>

@if (@Model != null)
{
	<div class="col">

		<a asp-controller="Language" asp-action="AddLanguage" class="btn btn-primary btn-sm">Add a Language</a>
		<a asp-controller="LanguagePerson" asp-action="AddLanguagePerson" class="btn btn-primary btn-sm">Add a Language to a Person</a>

	</div>

	<div class="row">
		<div class="col"><b>
			@(Html.DisplayNameFor(model => model.Id))
		</b>
		</div>
		<div class="col"><b>
			@(Html.DisplayNameFor(model => model.Name))
		</b>
		</div>
		<div class="col">
			&nbsp;
		</div>
	</div>


	@foreach (var item in Model)
	{

		<div class="row m-1">
			<div class="col">
				<label asp-for="@item.Id" />@item.Id
			</div>
			<div class="col">
				<label asp-for="@item.Name" />@item.Name
			</div>
			<div class="col">
				<a asp-controller="Language" asp-action="Delete" class="btn btn-danger btn-sm" value="Delete" asp-route-id="@item.Id" asp-route-name="@item.Name">Delete</a>

			</div>
		</div>
	}

}